### ISSUE TITLE
Trailing newline characters on filter strings read from a text file prevent proper matching

### ISSUE THREAD

**Issue by tsgolden** [WHOIGit/ifcb_classifier#8]
Hi @sbatchelder and @joefutrelle. I've been working to integrate `ifcb_classifier` into our IFCB processing pipeline here at Axiom. Overall, it's been great to work with, but I ran into a bug when trying to pull in filter strings from a text file.

The issue I was seeing was that when I ran something like `python neuston_net.py RUN ... --clobber --filter my-filters.txt`, I would just immediately get `RUN IS DONE` as if none of my filter strings had matched any of the bin object filepaths, even though the same filters matched if I passed them directly to `--filter`.

I dug in and tracked the issue down to trailing newline characters resulting from [this call](https://github.com/WHOIGit/ifcb_classifier/blob/master/neuston_net.py#L205) to `f.readlines()`. Basically each newline-delimited filter string still had its newline character on the end of it (because `readlines` doesn't remove them), which prevented it from matching with any of the bin object filepaths. I changed that line to `f.read().splitlines()`, and that got file-based filtering working again for me.

I noticed a similar pattern being used in [some places](https://github.com/WHOIGit/ifcb_classifier/blob/e1caa6e042684b4e541da9b690a82d6a0b6672d3/neuston_onnx.py#L100), but not in [others](https://github.com/WHOIGit/ifcb_classifier/blob/e1caa6e042684b4e541da9b690a82d6a0b6672d3/neuston_net.py#L222), so I'm assuming the issue I ran into was just an oversight. I have a fix on the fork we're currently running [here](https://github.com/tsgolden/ifcb_classifier/commit/62df3e3f5d203bea6a2ea42099d00af9a489e0ee) and would be happy to turn that into a pull request if you're open to contributions. If so, I can also fix the other occurences of this `readlines` pattern I ran across in the codebase.

**Comment by sbatchelder** [comment]
Hi @tsgolden,
Good catch! You are more than welcome to make a PR to fix this kind of readlines oversight, thank you for offering! I'm glad to hear you're otherwise finding the features helpful

**Comment by tsgolden** [comment]
Great, thanks! Just opened the [PR](https://github.com/WHOIGit/ifcb_classifier/pull/9)

**Comment by sbatchelder** [comment]
PR is merged, closing issue
